### ISSUE TITLE
Cannot compile any piece of code from this repo

### ISSUE THREAD

**Issue by B4tiste** [BDafflon/p5#2]
I stumbled upon this little set of python games that I wanted to try out, but I can't compile any of them, getting this error over and over again : 
```bash
ModuleNotFoundError: No module named 'core'
```

How did you manage to get core on your machine ? Are you using Python 2 ?

**Comment by B4tiste** [comment]
Solved by using the PyCharm package managed 😀

**Comment by BDafflon** [comment]
You can also copy the core.py file to the folder of your choice. 

on the other hand, these are games/projects used to teach python or distributed artificial intelligence. There is nothing "finished".

**Comment by B4tiste** [comment]
Oh I see, thanks for answering. I'm glad I made it work because all the functions in the core.py file makes pygame really easy to use
